{
 "title": "tickets-auth-service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[1m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_cpu_system_seconds_total",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}