apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411
        env:
        - name: STORAGE_TYPE
          value: mem
        - name: HTTP_COLLECTOR_ENABLED
          value: "true"
        - name: TRANSPORT_TYPE
          value: http
        - name: KUBERNETES_NAMESPACE
          value: default
        - name: QUERY_LOG_LEVEL
          value: DEBUG
---

apiVersion: v1
kind: Service
metadata:
  name: zipkin-serv
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
    nodePort: 32000
