apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: orders-srv
  endpoints:
  - path: /api/orders/metrics
    port: orders
    interval: 15s
