apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-data-tickets
  namespace: tickets-app
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
