apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
  namespace: orders-app
spec:
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: rohitbrk12345/orders
        ports:
        - containerPort: 5000
...
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
  labels:
    app: orders-srv
  namespace: orders-app
spec:
  selector:
    app: orders
  ports:
  - name: orders
    port: 5000
    protocol: TCP
    targetPort: 5000
