apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
  namespace: orders-app
type: Opaque
data:
  JWT_KEY: cm9oaXRfYnI=
  TRACING_URL: aHR0cDovL3ppcGtpbi1zZXJ2LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6OTQxMS9hcGkvdjIvc3BhbnM=
  NATS_CLIENT: bmF0czovL25hdHMtc3J2LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NDIyMg==
  POSTGRES_PASSWORD: b3JkZXJzIA0K
  POSTGRES_DB: b3JkZXJzZGIgDQo=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_HOST: b3JkZXJzLWRiLXNydg==
  POSTGRES_PORT: IjU0MzIi
  NODE_ENV: UFJPRA==
