apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: auth-srv
  endpoints:
  - path: /api/users/metrics
    port: auth
    interval: 15s
