apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: auths
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        envFrom:
        - secretRef:
            name: auth-secret
        image: rohitbrk12345/auth
---

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  labels:
    app: auth-srv
  namespace: auths
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 3000
    targetPort: 3000
