apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: auths
type: Opaque
data:
  JWT_KEY: cm9oaXRfYnI=
  TRACING_URL: aHR0cDovL3ppcGtpbi1zZXJ2Ojk0MTEvYXBpL3YyL3NwYW5z
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: YXV0aHM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_HOST: dGlja2V0LWRiLXNydg==
  POSTGRES_PORT: NTQzMg==
  NODE_ENV: UFJPRA==
