apiVersion: v1
kind: Secret
metadata:
  name: tickets-secret
  namespace: tickets-app
type: Opaque
data:
  JWT_KEY: cm9oaXRfYnI=
  TRACING_URL: aHR0cDovL3ppcGtpbi1zZXJ2LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6OTQxMS9hcGkvdjIvc3BhbnM=
  NATS_CLIENT: bmF0czovL25hdHMtc3J2LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NDIyMg==
  POSTGRES_PASSWORD: dGlja2V0cw==
  POSTGRES_DB: dGlja2V0cw==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_HOST: dGlja2V0LWRiLXNydg==
  POSTGRES_PORT: NTQzMg==
  NODE_ENV: UFJPRA==
