apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
  namespace: tickets-app
spec:
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: rohitbrk12345/tickets
        envFrom:
        - secretRef:
            name: tickets-secret
        ports:
        - containerPort: 4000
---

apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
  labels:
    app: tickets-srv
  namespace: tickets-app
spec:
  selector:
    app: tickets
  ports:
  - name: tickets
    port: 4000
    protocol: TCP
    targetPort: 4000
