name: deploy-tickets

on:
    push:
        branches:
            - main
        paths:
            - 'tickets/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: cd tickets && docker build -t rohitbrk12345/tickets .
            - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push rohitbrk12345/tickets