name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd payments && npm install && npm run test:ci

  format:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: |
            if ! npm run format:check; then
              npm run format
            fi
    continue-on-error: true

  scan:
    name: Docker Security Scan
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        working-directory: ./payments
        run: |
          docker build -t rohitbrk12345/payments:${{ github.sha }} .
      
      - name: install trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.48.0
      
      - name: Run Trivy Vulnerablity Scanner
        run: |
          trivy image \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            --no-progress \
            --format template \
            --template '@/usr/local/share/trivy/temp'
            -o trivy-results.sarif \
            rohitbrk12345/payments:${{ github.sha }}
        continue-on-error: true

      - name: Upload Trivy Scan Results to Github Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif